import { SessionProvider } from 'next-auth/react';
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
// import './katex.min.css'; // For KaTeX CSS
import 'katex/dist/katex.min.css';
import './github.css'; // For Highlight.js GitHub theme (or your chosen theme)
import { ThemeProvider } from "@/components/theme-provider"
import { MainLayoutWrapper } from '@/components/layout/main-layout-wrapper';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
         <ThemeProvider attribute="class" defaultTheme="system" enableSystem disableTransitionOnChange>
        <SessionProvider>
          <MainLayoutWrapper>{children}</MainLayoutWrapper>
        </SessionProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
